name: Release Helm Chart

on:
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get chart version from Chart.yaml
        id: chart-version
        run: |
          CHART_VERSION=$(grep '^version:' charts/ory-admin/Chart.yaml | awk '{print $2}')
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          helm package charts/ory-admin --destination .release

      - name: Push Helm chart to GHCR
        run: |
          helm push .release/ory-admin-${{ steps.chart-version.outputs.version }}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
